Repository InformedSolutions/OFS-MORE-Nanny-Gateway, pull requests merged in 2018-10, with the labels that each got.

#27 CCN3-1589: Master summary table updates
  application/models/applicant_home_address.py
  application/models/applicant_personal_details.py
  application/models/childcare_address.py
  application/models/childcare_training.py
  application/models/dbs_check.py
  application/models/first_aid.py
  application/models/insurance_cover.py
  application/models/nanny_application.py
Labels: user story

#29 feat/CCN3-1825/updating-gateway-for-your-children-nannies
  application/migrations/0042_applicantpersonaldetails_your_children.py
  application/models/applicant_personal_details.py
Labels: backend

#30 feat/CCN3-1825/updating-gateway-for-your-children-nannies
  application/migrations/0043_auto_20181015_1254.py
  application/models/nanny_application.py
Labels: backend, enhancement

#34 feat/CCN3-1825/nannies-update-personal-details-task-for-known-children
  application/models/applicant_personal_details.py
Labels: enhancement

#35 Fixed link field name
  application/models/applicant_personal_details.py
Labels: backend

#37 fix/update-timezone
  nanny_gateway/settings/base.py
Labels: bug
