Repository InformedSolutions/OFS-MORE-Nanny-Gateway, pull requests merged in 2019-03, with the labels that each got.

#52 Fix/ccn3 1913/lived abroad personal details
  application/migrations/0058_remove_applicantpersonaldetails_lived_abroad.py
  application/migrations/0059_remove_applicantpersonaldetails_post_certificate_declaration.py
  application/migrations/0060_merge_20190301_1236.py
  application/models/applicant_personal_details.py
  application/tests/test_audit_log.py
Labels: enhancement

#55 Fix/ccn3 2296/date formatting
  application/models/applicant_personal_details.py
Labels: bug

#56 Feat/ccn3 2102/arc nannies previous registration
  application/migrations/0061_nannypreviousregistrationdetails.py
  application/migrations/0062_nannypreviousregistrationdetails.py
  application/migrations/0063_merge_20190311_1501.py
  application/migrations/0064_auto_20190311_1530.py
  application/migrations/0065_remove_nannypreviousregistrationdetails_personal_detail_id.py
  application/migrations/0066_merge_20190315_1642.py
  application/models/__init__.py
  application/models/arc_previous_registration_details.py
  application/views.py
  nanny_gateway/urls.py
Labels: backend, enhancement

#57 Fix/dependency update
  requirements.txt
Labels: backend, enhancement

#61 Feat/ccn3 2100/nannies previous addresses
  application/migrations/0066_previousaddress.py
  application/migrations/0068_merge_20190322_1517.py
  application/models/__init__.py
  application/models/applicant_home_address.py
  application/models/previous_address.py
  application/views.py
  nanny_gateway/urls.py
Labels: backend, user story

#65 feat/CCN3-1835/reminder-email
  application/migrations/0066_nannyapplication_application_expiry_email_sent.py
  application/models/nanny_application.py
Labels: backend, enhancement
